### PR TITLE
Move to Bencher CLI GitHub Action

### PR DESCRIPTION
**Pull request by epompeii**
Move Bencher in CI over to the [Bencher CLI GitHub Action](https://github.com/marketplace/actions/bencher-cli).

Also add a Bencher perf image to the readme to illustrate the similarities in performance for `log4rs` vs `trace4rs`.

### CODE REVIEW

**Comment by epompeii** [comment]
Is `BENCHER_API_TOKEN` still set as a **repository** secret?

I sanity checked by running a nearly identical test on my own repo and things worked:
- https://github.com/bencherdev/bencher/commit/30dd1d4b2d23a61fdcb55f9fcac296c354463f55
- https://github.com/bencherdev/bencher/actions/runs/4460440610/jobs/7833580893

And on the PR branch as well:
- https://github.com/epompeii/trace4rs/actions/runs/4469180005

I also checked the API token locally, and it is still valid and working.

**Comment by epompeii** [comment]
I believe what is happening is because I don't have the appropriate permissions on the repository GitHub is not actually providing the secret. This is in order to prevent randos from being able to leak/exfiltrate repository secrets.

```
error: a value is required for '--token <TOKEN>' but none was supplied
```

https://github.com/imperva/trace4rs/actions/runs/4479249673/jobs/7872979410?pr=13

**Comment by gadunga** [comment]
I'll take a look at the settings and send you a message.

**Comment by gadunga** [comment]
It appears that I do not have access to that. We'll need to talk to someone about getting access to that.

**Pull request merged**
